-- +migrate Up
CREATE TABLE IF NOT EXISTS people (
    Id SERIAL NOT NULL PRIMARY KEY,
    Name varchar(255),
    Age int
);

insert into people (Name, Age) values ('Karoly Varian', 51);
insert into people (Name, Age) values ('Cchaddie Prangley', 41);
insert into people (Name, Age) values ('Happy Ben-Aharon', 85);
insert into people (Name, Age) values ('Billy Barnaclough', 84);
insert into people (Name, Age) values ('Shepard Reubel', 58);
insert into people (Name, Age) values ('Geri Saxby', 70);
insert into people (Name, Age) values ('Samaria Charke', 47);
insert into people (Name, Age) values ('Eward Coomes', 56);
insert into people (Name, Age) values ('Cindie Smeuin', 61);
insert into people (Name, Age) values ('Hadleigh McAulay', 41);
insert into people (Name, Age) values ('Elsa Akroyd', 43);
insert into people (Name, Age) values ('Neall Willoughley', 30);
insert into people (Name, Age) values ('Tod Gradon', 48);
insert into people (Name, Age) values ('Pip Lotze', 37);
insert into people (Name, Age) values ('Caldwell Dedenham', 63);
insert into people (Name, Age) values ('Betsey Trowell', 85);
insert into people (Name, Age) values ('Andria Garwill', 69);
insert into people (Name, Age) values ('Lorenzo Jennings', 45);
insert into people (Name, Age) values ('Johnna Barwise', 48);
insert into people (Name, Age) values ('Paxon Halvosen', 53);
insert into people (Name, Age) values ('Steffane Sibbson', 39);
insert into people (Name, Age) values ('Sophi Dupoy', 43);
insert into people (Name, Age) values ('Betsy Hymus', 29);
insert into people (Name, Age) values ('Edith Cagan', 26);
insert into people (Name, Age) values ('Charita Dennes', 53);
insert into people (Name, Age) values ('Bertine O''Shiels', 86);
insert into people (Name, Age) values ('Willy Heikkinen', 88);
insert into people (Name, Age) values ('Mano Fitzroy', 21);
insert into people (Name, Age) values ('Stephanus Burds', 59);
insert into people (Name, Age) values ('Lev Lackmann', 61);
insert into people (Name, Age) values ('Arlinda Grieswood', 85);
insert into people (Name, Age) values ('Lebbie Punshon', 55);
insert into people (Name, Age) values ('Isadore Remmers', 24);
insert into people (Name, Age) values ('Ferd Kornyakov', 45);
insert into people (Name, Age) values ('Dory Merriton', 72);
insert into people (Name, Age) values ('Chad McGillecole', 90);
insert into people (Name, Age) values ('Miles Lejeune', 43);
insert into people (Name, Age) values ('Alwyn Tanzig', 85);
insert into people (Name, Age) values ('Kiel Lutwyche', 37);
insert into people (Name, Age) values ('Leontine Lunbech', 80);
insert into people (Name, Age) values ('Gayleen Di Biasi', 80);
insert into people (Name, Age) values ('Blair Arno', 50);
insert into people (Name, Age) values ('Olia Edmundson', 23);
insert into people (Name, Age) values ('Vicky Hawkings', 40);
insert into people (Name, Age) values ('Jeromy Flahy', 52);
insert into people (Name, Age) values ('Karia Pevie', 73);
insert into people (Name, Age) values ('Horace Munslow', 39);
insert into people (Name, Age) values ('Normy Jowitt', 34);
insert into people (Name, Age) values ('Caresa Colson', 56);
insert into people (Name, Age) values ('Alia Hulett', 53);
insert into people (Name, Age) values ('Arvy Paumier', 66);
insert into people (Name, Age) values ('Claudell Ibarra', 41);
insert into people (Name, Age) values ('Boyce Bewly', 56);
insert into people (Name, Age) values ('Augustina Colegrove', 26);
insert into people (Name, Age) values ('Lorettalorna Bartel', 45);
insert into people (Name, Age) values ('Filberto Deplacido', 38);
insert into people (Name, Age) values ('Cherrita Kubu', 80);
insert into people (Name, Age) values ('Ailbert Lorroway', 49);
insert into people (Name, Age) values ('Harold Overington', 26);
insert into people (Name, Age) values ('Ellyn Rossbrooke', 37);
insert into people (Name, Age) values ('Clarence Karlsson', 68);
insert into people (Name, Age) values ('Joete Curness', 38);
insert into people (Name, Age) values ('Prinz Brandoni', 23);
insert into people (Name, Age) values ('Gennifer Seeley', 60);
insert into people (Name, Age) values ('Arleen Garcia', 35);
insert into people (Name, Age) values ('Edgardo Dan', 85);
insert into people (Name, Age) values ('Cari Shepley', 76);
insert into people (Name, Age) values ('Sarajane Giannoni', 63);
insert into people (Name, Age) values ('Mack Whitfeld', 65);
insert into people (Name, Age) values ('Elli Weatherill', 57);
insert into people (Name, Age) values ('Trev Spere', 79);
insert into people (Name, Age) values ('Ileana Mash', 42);
insert into people (Name, Age) values ('Vinny Perche', 49);
insert into people (Name, Age) values ('Leilah Hewkin', 23);
insert into people (Name, Age) values ('Dugald Langtree', 34);
insert into people (Name, Age) values ('Ericka Poone', 69);
insert into people (Name, Age) values ('Hetty Stearn', 71);
insert into people (Name, Age) values ('Analise Wilfling', 21);
insert into people (Name, Age) values ('Dee Sture', 88);
insert into people (Name, Age) values ('Livia Sisey', 35);
insert into people (Name, Age) values ('Libbie Pignon', 78);
insert into people (Name, Age) values ('Gilbertina Collard', 55);
insert into people (Name, Age) values ('Kalila Gleader', 39);
insert into people (Name, Age) values ('Cristabel McElory', 71);
insert into people (Name, Age) values ('Revkah Ossipenko', 40);
insert into people (Name, Age) values ('Ralina Eales', 64);
insert into people (Name, Age) values ('Dave Scay', 87);
insert into people (Name, Age) values ('Jaclin Willimot', 24);
insert into people (Name, Age) values ('Mead Gronous', 84);
insert into people (Name, Age) values ('Hurlee Wreath', 47);
insert into people (Name, Age) values ('Oliver SavaAge', 77);
insert into people (Name, Age) values ('Trix Firpi', 55);
insert into people (Name, Age) values ('Milzie Prester', 87);
insert into people (Name, Age) values ('Alecia Tooze', 62);
insert into people (Name, Age) values ('Stacey McKmurrie', 44);
insert into people (Name, Age) values ('Pincus Kem', 23);
insert into people (Name, Age) values ('Natalya Northwood', 28);
insert into people (Name, Age) values ('Adelbert Scrange', 28);
insert into people (Name, Age) values ('Freeman Monaghan', 63);
insert into people (Name, Age) values ('Monty Rash', 64);


-- +migrate Down
DROP TABLE people;